name: pyprt-examples-py312
channels:
  - defaults
dependencies:
  - python=3.12
  - esri::pyprt
  - esri::arcgis
  - numpy
  - pandas
  - pyqt
  - scipy
  - shapely
  - notebook<7.0
  - ipywidgets
  - conda-forge::vtk>=9.2
  - conda-forge::pyvista
  - conda-forge::trame
  - conda-forge::trame-vtk
  - conda-forge::trame-vuetify
  - conda-forge::vispy
  - conda-forge::ipyvtklink
