name: pyprt-examples-py310
channels:
  - defaults
dependencies:
  - python=3.10
  - esri::pyprt
  - esri::arcgis<2.4.0
  - numpy
  - pandas
  - pyqt
  - scipy
  - shapely
  - notebook<7.0
  - conda-forge::vtk>=9.2
  - conda-forge::pyvista
  - conda-forge::trame
  - conda-forge::trame-vtk
  - conda-forge::trame-vuetify
  - conda-forge::vispy
  - conda-forge::ipyvtklink
  