name: pyprt-examples-py39
channels:
  - defaults
dependencies:
  - python=3.9
  - esri::pyprt
  - esri::arcgis
  - scipy
  - shapely
  - conda-forge::vispy
  - conda-forge::pyvista
  - conda-forge::ipyvtklink
  - notebook
