name: pyprt-examples
channels:
  - esri
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip
  - python=3.9
  - pyprt  
  - notebook
  - scipy
  - vispy
  - ipywidgets
  - pip:
    - pygel3d
    - pyqt5
