name: pyprt-examples-py311
channels:
  - defaults
dependencies:
  - python=3.11
  - esri::pyprt
  - scipy
  - conda-forge::vispy
  - conda-forge::pyvista
  - conda-forge::ipyvtklink
  - conda-forge::trame
  - notebook
  - pandas
  - pyqt
  - numpy<1.24.0
