name: pyprt-examples-py36
channels:
  - esri
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - pip
  - python=3.6
  - pyprt  
  - arcgis=2.0.0
  - notebook
  - scipy
  - shapely=1.8.2
  - vispy
  - pip:
    - pygel3d
    - pyqt5
