name: pyprt-examples-py313
channels:
  - defaults
dependencies:
  - python=3.13
  - esri::arcgis
  - numpy
  - pandas
  - pyqt
  - scipy
  - shapely
  - notebook
  - conda-forge::vtk
  - conda-forge::pyvista
  - conda-forge::trame
  - conda-forge::trame-vtk
  - conda-forge::trame-vuetify
  - conda-forge::vispy
  - conda-forge::ipyvtklink
