name: pyprt-examples
channels:
  - esri
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.8
  - pyprt  
  - arcgis=2.0.0
  - scipy
  - vispy
  - pyvista
  - ipyvtklink
  - pip:
    - notebook
    - pyqt5
