name: pyprt-examples-py39
channels:
  - esri
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.9
  - pyprt
  - arcgis
  - scipy
  - shapely=1.8.5
  - vispy
  - pyvista
  - ipyvtklink
  - pip:
    - notebook
    - pyqt5
