name: pyprt-examples-py38
channels:
  - defaults
dependencies:
  - python=3.8
  - esri::pyprt
  - esri::arcgis
  - scipy
  - shapely
  - vispy
  - conda-forge::pyvista
  - conda-forge::ipyvtklink
  - notebook
  - pyqt
